name: Update

on:
  workflow_dispatch:
  schedule:
    # Every Monday at midnight.
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checking out the repository.
      - name: Checkout repository.
        uses: actions/checkout@v2.3.4
      # Installing the Python version required.
      - name: Setup Python.
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      # Installing required dependencies.
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Running the script for scrapping.
      - name: Run the updating script.
        run: |          
          python update.py          
          git add README.md
          git add public/data.json
          git config --global user.name "whoswhobot"
          git config --global user.email "whoswho@example.com"                
          git commit -m "Updated whoswho: `date +'%Y-%m-%d %H:%M:%S'`" || true
        env:
          WHOSWHO_SHEET_URL: ${{ secrets.WHOSWHO_SHEET_URL }}
      # Pushing the changes.
      - name: Push the changes.
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
